APPLY_FIXES: none

DISABLE_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_TRIVY

FILEIO_REPORTER: false

HTML_DJLINT_ARGUMENTS: --ignore "H023,H031"

LINTER_RULES_PATH: config

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: \.github/actions/spelling

SHOW_ELAPSED_TIME: true
